import { type SchemaTypeDefinition } from 'sanity'
import infoSection from './infoSection'
import infoPopup from './infoPopup'
import banner from './banner'
import faqSection from './faqSection'
import faqPopup from './faqPopup'
import event from './event'
import churchLeader from './churchLeader'
import reverendList from './reverendList'
import deaconList from './deaconList'
import ministryLeadList from './ministryLeadList'
import reverend from './reverend'
import faq from './faq'
import eventsPopup from './eventsPopup'
import communityActivity from './communityLifeActivities'
import aboutPage from './aboutPage'
import homePage from './homePage'
import testimony from './testimony'
import contactEmail from './contactEmail'
import contactPhone from './contactPhone'
import joinMinistryPage from './joinMinistryPage'

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [infoSection, infoPopup, banner, faq, faqSection, faqPopup, event, eventsPopup, churchLeader, reverend, reverendList, deaconList, ministryLeadList, communityActivity, aboutPage, homePage, joinMinistryPage, testimony, contactEmail, contactPhone],
}
